version: '3'
services:
  postgres:
    image: postgres:9.6
    container_name: unexpected-knex
    environment:
      POSTGRES_PASSWORD: postgres

  unexpected-knex:
    build: .
    command: npm run test:mocha
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    environment:
      PGHOST: postgres
